services:
  paybutton:
    container_name: paybutton-dev
    restart: always
    depends_on:
      - db
      - users-service
      - cache
    build: .
    env_file:
      - .env.from-dump
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/home/node/src
    command: bash ./scripts/paybutton-server-start.sh
  db:
    container_name: paybutton-db
    image: mariadb
    user: root
    build:
      context: .
      dockerfile: './scripts/db/Dockerfile'
    restart: always
    env_file:
      - .env
      - .env.local
      - .env.from-dump
    environment:
      MYSQL_ROOT_PASSWORD: ${MAIN_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MAIN_DB_NAME}
      MYSQL_USER: ${MAIN_DB_USER}
      MYSQL_PASSWORD: ${MAIN_DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./scripts/db/mysql-config.cnf:/etc/mysql/conf.d/mysql-config.cnf
      - ./scripts/db-entrypoint.sh:/docker-entrypoint-initdb.d/1-db-entrypoint.sh
      - ./scripts/db/init-test-db.sql:/home/mysql/raw_entrypoint/2-init-test-db.sql
      - ./scripts/db/init-supertokens-db.sql:/home/mysql/raw_entrypoint/3-init-supertokens-db.sql
      - ./scripts/db/prisma-shadow-db-fix.sql:/home/mysql/raw_entrypoint/4-prisma-shadow-db-fix.sql
      - ./dump.sql:/home/mysql/raw_entrypoint/5-dump.sql

  users-service:
    container_name: paybutton-users-service
    depends_on:
      - db
      - cache
    image: registry.supertokens.io/supertokens/supertokens-mysql
    restart: always
    ports:
      - 3567:3567
    environment:
      MYSQL_DATABASE_NAME: supertokens
      MYSQL_USER: ${SUPERTOKENS_DB_USER}
      MYSQL_PASSWORD: ${SUPERTOKENS_DB_PASSWORD}
      MYSQL_HOST: ${MAIN_DB_HOST}
      MYSQL_PORT: ${MAIN_DB_PORT}

  cache:
    container_name: paybutton-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data/redis:z
      - ./scripts:/data/scripts
    command: sh -c "sed -i 's/\\r//g' ./scripts/redis-start.sh && sh ./scripts/redis-start.sh"
