version: "3.9"
services:
  paybutton:
    depends_on: 
      - mysql
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app/src
    command: sh -c "yarn db:migrate && yarn dev"
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paybutton
      MYSQL_USER: paybutton
      MYSQL_PASSWORD: paybutton
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
