version: "3.9"
services:
  paybutton:
    container_name: paybutton-dev
    restart: always
    depends_on: 
      - db
      - users-service
      - cache
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/src
    command: sh -c "yarn && yarn prisma migrate dev && yarn prisma db seed && yarn dev"
  db:
    container_name: paybutton-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paybutton
      MYSQL_USER: paybutton
      MYSQL_PASSWORD: paybutton
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./scripts/db/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
      - ./scripts/db/init-supertokens-db.sql:/docker-entrypoint-initdb.d/init-supertokens-db.sql
      - ./scripts/db/prisma-shadow-db-fix.sql:/docker-entrypoint-initdb.d/prisma-shadow-db-fix.sql

  users-service:
    container_name: paybutton-users-service
    depends_on:
      - db
      - cache
    image: registry.supertokens.io/supertokens/supertokens-mysql
    restart: always
    ports:
      - 3567:3567
    environment:
      MYSQL_DATABASE_NAME: supertokens
      MYSQL_USER: supertokens
      MYSQL_PASSWORD: supertokens
      MYSQL_HOST: db
      MYSQL_PORT: 3306

  cache:
    container_name: paybutton-cache
    image: redis:6.2-alpine
    restart: always
    user: 1000:1000
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data/redis:z
    # dump the dataset each 20 seconds if there was at least 1 change
    command: sh -c "umask 000 && redis-server /data/redis/redis.conf --save 20 1 --loglevel warning"
