version: "3.9"
services:
  paybutton:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src
    links: 
      - db
    command: npm run dev
  db:
    image: mysql/mysql-server:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paybutton
volumes:
   mysql_data:
