version: "3.9"
services:
  paybutton:
    container_name: paybutton-dev
    restart: always
    depends_on:
      - db
      - users-service
      - cache
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/home/node/src
      - ./logs:/home/node/.pm2/logs
    command: bash ./scripts/paybutton-server-start.sh

  cache:
    container_name: paybutton-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data/redis:z
      - ./scripts:/data/scripts
    command: sh -c "sed -i 's/\\r//g' ./scripts/redis-start.sh && sh ./scripts/redis-start.sh"
