
name: post-deploy-url

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-for-deploy-and-post-url:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Wait Netlify
        uses: denar90/wait-for-netlify-action@v2.0.2
        id: waitForNetlify
        with:
          site_id: "fc93e6dd-5767-41e1-882b-5d7eea06554e"
      - name: Post deploy url
        uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Successfully deployed on: https://${{ steps.extract_branch.outputs.branch }}.paybutton.io 

