name: Check Commit Depends On 

on:
  pull_request:
    branches: [ master ]

jobs:
  commit-depends-on:
    name: Commit Depends On Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
         ref: ${{github.event.after}}
      - name: Get Commit Message
        id: depends_on
        run: |
          MSG=$(git log --format=%B -n 1 HEAD | { grep "Depends on" || true; })
          echo $MSG
          if [[ ! -z $MSG ]]
          then
            echo "::set-output name=COMMIT_DEPENDS_ON::${MSG}"
          else
            echo "::set-output name=COMMIT_DEPENDS_ON::false"
          fi
      - name: Get branch name
        if: ${{ steps.depends_on.outputs.COMMIT_DEPENDS_ON != 'false' }}
        uses: mad9000/actions-find-and-replace-string@1
        id: findandreplace
        with:
          source: ${{ steps.depends_on.outputs.COMMIT_DEPENDS_ON }}
          find: 'Depends on: '
          replace: ''
      - name: Add label to PR
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.depends_on.outputs.COMMIT_DEPENDS_ON  != 'false' }}
        with:
          labels: Depends on ${{ steps.findandreplace.outputs.value }}
      - name: Check if dependant branch is already merged
        if:  ${{ steps.depends_on.outputs.COMMIT_DEPENDS_ON != false && steps.findandreplace.outputs.value != '' }}
        env:
          branch_name: ${{ steps.findandreplace.outputs.value }}
          error_message: ""
        run: |
            # make file runnable, might not be necessary
            chmod +x "${GITHUB_WORKSPACE}/.github/depends_on_check.sh"

            # run script
            "${GITHUB_WORKSPACE}/.github/depends_on_check.sh"


