name: Lint and check format of source code
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Lint and check format of diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Check format and style
        run: yarn ci:format-check
      - name: Lint
        run: yarn ci:lint
