name: Check Pull Request Dependencies

on:
  pull_request:
    branches: [ main ]
    types: [ opened, syncronize, edited ]

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
