name: Integration Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn
      - name: Spin up required database containers
        run: docker-compose up -d db users-service
      - name: Run integration tests
        run: make test-integration
