name: Pull Request Tests
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn
      - name: Run unit tests
        run: make github-test-unit
      - name: Add local env file
        run: touch .env.local
      - name: Spin up containers
        run: docker compose up --build -d paybutton db users-service cache
      - name: WIP Show dev logs before
        run: ls
      - name: Run integration tests
        run: make github-test-integration
      - name: Show dev logs
        if: always()
        run: make logs-dev
