name: Lint, Check, Format and Unit Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Lint, Check, Format and Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check no tests will be run with `.only`
        run: make no-isolated-tests
      - name: Install dependencies
        run: yarn
      - name: Lint and check format
        run: make lint-master
      - name: Run unit tests
        run: |
          yarn
          make test-unit
