name: Lint, Check, Format and Unit Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Lint, Check, Format and Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint and check format
        run: make lint-master
      - name: Run unit tests
        run: |
          make dev
          make test-unit
