name: Lint and check format of source code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Lint and check format of diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn
      - name: Check format and style
        run: yarn ci:format-check
      - name: Lint
        run: yarn ci:lint
