name: Lint and check format of source code
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Lint, format and test diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint and check format
        run: make lint-master
      - name: Run unit and integration tests
        run: make test
